services:
  webdav:
    image: webdav-server
    environment:
      - WEBDAV_USERNAME=youruser
      - WEBDAV_PASSWORD=yourpass
      - WEBDAV_CRYPTO_PASSWORD=yourcryptopass
      - WEBDAV_DATA_DIR=/data
      - WEBDAV_PORT=8080
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped